- name: Check if maven already exists
  stat:
    path: /usr/local/devenv/maven
  register: p

- name: Download maven
  get_url:
    url: http://www.nic.funet.fi/pub/mirrors/apache.org/maven/maven-3/{{ maven_version }}/binaries/apache-maven-{{ maven_version }}-bin.tar.gz
    dest: /tmp/maven.tar.gz
    mode: 0666
    checksum: sha1:{{ maven_checksum }}
  when: p.stat.exists == False

- name: Create directory for maven
  file:
    path: /usr/local/devenv/maven
    state: directory
    mode: 0755
    owner: "{{ ansible_user_id }}"
  become: true
  when: p.stat.exists == False

- name: Unpack maven
  unarchive:
    src: /tmp/maven.tar.gz
    dest: /usr/local/devenv/maven
    extra_opts: [--strip-components=1]
  when: p.stat.exists == False

- name: Delete temporary file
  file:
    path: /tmp/maven.tar.gz
    state: absent

- name: Create symbolic link
  file:
    src: /usr/local/devenv/maven/bin/mvn
    dest: /usr/local/bin/mvn
    state: link
  become: true
