- name: Install java package repository
  apt_repository:
    repo: ppa:webupd8team/java
    state: present
  become: true

- name: Accept oracle license
  shell: echo debconf shared/accepted-oracle-license-v1-1 select true | debconf-set-selections
  become: true  

- name: Install latest version of oracle java8
  apt:
    name: oracle-java8-installer
    state: latest
  become: true

- name: Set oracle java as default
  apt:
    name: oracle-java8-set-default
    state: present
  become: true

